STATE_LIST = [
    "01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07",
    "08",
    "09",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
]
STATE_DICT = {
    "01": "Johor",
    "02": "Kedah",
    "03": "Kelantan",
    "04": "Melaka",
    "05": "Negeri Sembilan",
    "06": "Pahang",
    "07": "Pulau Pinang",
    "08": "Perak",
    "09": "Perlis",
    "10": "Selangor",
    "11": "Terengganu",
    "12": "Sabah",
    "13": "Sarawak",
    "14": "W.P. Kuala Lumpur",
    "15": "W.P. Labuan",
    "16": "W.P. Putrajaya",
}
# CATEGORY_LIST = ["BG", "FM", "KO", "MD", "OEM", "PE", "PL", "PR", "PS"]
CATEGORY_LIST = [ "PE"]

CATEGORY_DICT = {
    "BG": "Barang Gunaan",
    "FM": "Farmaseutikal",
    "KO": "Kosmetik dan Dandanan Diri",
    "MD": "Peranti Perubatan",
    "OEM": "Pengilangan Kontrak / Original Equipment Manufacturing(OEM)",
    "PE": "Premis Makanan",
    "PL": "Logistik",
    "PR": "Produk Makanan / Minuman",
    "PS": "Rumah Sembelihan",
}
# SUB_CATEGORY_LIST = ["CO", "PE", "HO"]
SUB_CATEGORY_LIST = ["PE"]

STATE_CITY_MAPPING = {
    "Johor": [
        "Johor Bahru",
        "Tebrau",
        "Pasir Gudang",
        "Bukit Indah",
        "Skudai",
        "Kluang",
        "Batu Pahat",
        "Muar",
        "Ulu Tiram",
        "Senai",
        "Segamat",
        "Kulai",
        "Kota Tinggi",
        "Pontian Kechil",
        "Tangkak",
        "Bukit Bakri",
        "Yong Peng",
        "Pekan Nenas",
        "Labis",
        "Mersing",
        "Simpang Renggam",
        "Parit Raja",
        "Kelapa Sawit",
        "Buloh Kasap",
        "Chaah",
        "Johor Bharu",
        "Pontian",
        "Gelang Patah",
    ],
    "Kedah": [
        "Sungai Petani",
        "Alor Setar",
        "Kulim",
        "Jitra / Kubang Pasu",
        "Baling",
        "Pendang",
        "Langkawi",
        "Yan",
        "Sik",
        "Kuala Nerang",
        "Pokok Sena",
        "Bandar Baharu",
        "Kota Setar",
        "Kuala Muda"

    ],
    "Kelantan": [
        "Kota Bharu",
        "Pangkal Kalong",
        "Tanah Merah",
        "Peringat",
        "Wakaf Baru",
        "Kadok",
        "Pasir Mas",
        "Gua Musang",
        "Kuala Krai",
        "Tumpat"
    ],
    "Melaka": [
        "Bandaraya Melaka",
        "Bukit Baru",
        "Ayer Keroh",
        "Klebang",
        "Masjid Tanah",
        "Sungai Udang",
        "Batu Berendam",
        "Alor Gajah",
        "Bukit Rambai",
        "Ayer Molek",
        "Bemban",
        "Kuala Sungai Baru",
        "Pulau Sebang",
        "Jasin",
        "Melaka Tengah"
    ],
    "Negeri Sembilan": [
        "Seremban",
        "Port Dickson",
        "Nilai",
        "Bahau",
        "Tampin",
        "Kuala Pilah"
    ],
    "Pahang": [
        "Kuantan",
        "Temerloh",
        "Bentong",
        "Mentakab",
        "Raub",
        "Jerantut",
        "Pekan",
        "Kuala Lipis",
        "Bandar Jengka",
        "Bukit Tinggi"
    ],
    "Perak": [
        "Ipoh",
        "Taiping",
        "Sitiawan",
        "Simpang Empat",
        "Teluk Intan",
        "Batu Gajah",
        "Lumut",
        "Kampung Koh",
        "Kuala Kangsar",
        "Sungai Siput Utara",
        "Tapah",
        "Bidor",
        "Parit Buntar",
        "Ayer Tawar",
        "Bagan Serai",
        "Tanjung Malim",
        "Lawan Kuda Baharu",
        "Pantai Remis",
        "Kampar",
        "Changkat Jering",
        "Kinta",
        "Larut Matang Dan Selama",
        "Manjung",
        "Hilir Perak",
        "Perak Tengah",
        "Kerian",
        "Batang Padang",
        "Sg. Siput"
    ],
    "Perlis": [
        "Kangar",
        "Kuala Perlis"
    ],
    "Pulau Pinang": [
        "Bukit Mertajam",
        "Georgetown",
        "Sungai Ara",
        "Gelugor",
        "Ayer Itam",
        "Butterworth",
        "Perai",
        "Nibong Tebal",
        "Permatang Kucing",
        "Tanjung Tokong",
        "Kepala Batas",
        "Tanjung Bungah",
        "Juru",
        "Barat Daya",
        "Timor Laut",

    ],
    "Sabah": [
        "Kota Kinabalu",
        "Sandakan",
        "Tawau",
        "Lahad Datu",
        "Keningau",
        "Putatan",
        "Donggongon",
        "Semporna",
        "Kudat",
        "Kunak",
        "Papar",
        "Ranau",
        "Beaufort",
        "Kinarut",
        "Kota Belud"
    ],
    "Sarawak": [
        "Kuching",
        "Miri",
        "Sibu",
        "Bintulu",
        "Limbang",
        "Sarikei",
        "Sri Aman",
        "Kapit",
        "Batu Delapan Bazaar",
        "Kota Samarahan"
    ],
    "Selangor": [
        "Subang Jaya",
        "Klang",
        "Ampang Jaya",
        "Shah Alam",
        "Petaling Jaya",
        "Cheras",
        "Kajang",
        "Selayang Baru",
        "Rawang",
        "Taman Greenwood",
        "Semenyih",
        "Banting",
        "Balakong",
        "Gombak Setia",
        "Kuala Selangor",
        "Serendah",
        "Bukit Beruntung",
        "Pengkalan Kundang",
        "Jenjarom",
        "Sungai Besar",
        "Batu Arang",
        "Tanjung Sepat",
        "Kuang",
        "Kuala Kubu Baharu",
        "Batang Berjuntai",
        "Bandar Baru Salak Tinggi",
        "Sekinchan",
        "Sabak",
        "Tanjung Karang",
        "Beranang",
        "Sungai Pelek",
        "Sepang",
        "Puchong",
        "Petaling",
        "Hulu Langat",
        "Kuala Langat",
        "Hulu Selangor",
        "Gombak"


    ],
    "Terengganu": [
        "Kuala Terengganu",
        "Chukai",
        "Dungun",
        "Kerteh",
        "Kuala Berang",
        "Marang",
        "Paka",
        "Jerteh"
    ],
    "Wilayah Persekutuan": [
        "Kuala Lumpur",
        "Labuan",
        "Putrajaya"
    ]
}