STATE_LIST = [
    "01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07",
    "08",
    "09",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
]
STATE_DICT = {
    "01": "Johor",
    "02": "Kedah",
    "03": "Kelantan",
    "04": "Melaka",
    "05": "Negeri Sembilan",
    "06": "Pahang",
    "07": "Pulau Pinang",
    "08": "Perak",
    "09": "Perlis",
    "10": "Selangor",
    "11": "Terengganu",
    "12": "Sabah",
    "13": "Sarawak",
    "14": "W.P. Kuala Lumpur",
    "15": "W.P. Labuan",
    "16": "W.P. Putrajaya",
}
CATEGORY_LIST = ["BG", "FM", "KO", "MD", "OEM", "PE", "PL", "PR", "PS"]

CATEGORY_DICT = {
    "BG": "Barang Gunaan",
    "FM": "Farmaseutikal",
    "KO": "Kosmetik dan Dandanan Diri",
    "MD": "Peranti Perubatan",
    "OEM": "Pengilangan Kontrak / Original Equipment Manufacturing(OEM)",
    "PE": "Premis Makanan",
    "PL": "Logistik",
    "PR": "Produk Makanan / Minuman",
    "PS": "Rumah Sembelihan",
}
